In [12]:
import re
s = '*/24#5%7&9*3@'
digits = re.findall(r'[0-9]',s)
for i in range(len(digits)):
    digits[i] = int(digits[i])
    
non_digit_n = len(s)-len(digits)
print(non_digit_n)
for i in digits:
    if i%2 == 0:
        print(i,end = ',')
for i in digits:
    if i%2 != 0:
        print(i, end = ',')

7
2,4,5,7,9,3,

In [1]:
from array import *

In [3]:
my_array = array('i',[1,2,3,4,5,6])

In [4]:
for i in my_array:
    print(i)

1
2
3
4
5
6


In [5]:
my_array.append(7) # append method add up at last

In [6]:
my_array

array('i', [1, 2, 3, 4, 5, 6, 7])

In [7]:
my_array.insert(0,0)
my_array # here time complexity is n

array('i', [0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
my_array2 = array('i',[9,5,3,2])
my_array.extend(my_array2)

In [10]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 9, 5, 3, 2])

In [11]:
my_array.buffer_info()

(1269066664176, 12)

In [13]:
my_array.count(5) # 5 has appeared 2 times

2

In [33]:
# array traversal in two dimension
import numpy as np
twod_array = np.array([[1,2,3],[3,4,6],[4,3,5],[-1,0,30]])
twod_array

array([[ 1,  2,  3],
       [ 3,  4,  6],
       [ 4,  3,  5],
       [-1,  0, 30]])

In [42]:
def find_element(key):
    for i in range(twod_array.shape[0]):
        for j in range(twod_array.shape[1]):
            if twod_array[i][j] == key:
                return f"key found at {(i,j)}"
    return 'key not found'

In [43]:
find_element(30)

'key found at (3, 2)'

In [34]:
twod_array.shape

(4, 3)

In [44]:
# deletionof rows
new_array = np.delete(twod_array, 0, axis = 0)

In [45]:
new_array

array([[ 3,  4,  6],
       [ 4,  3,  5],
       [-1,  0, 30]])

In [46]:
new_array = np.delete(new_array, -1, axis = 1)

In [47]:
new_array

array([[ 3,  4],
       [ 4,  3],
       [-1,  0]])

In [1]:
# finding pair  of number having sum = n
def findpair(nums, target):
    result = []
    for i in range(len(nums)):
        for j in range(i+1,len(nums)):
            if nums[i]+nums[j] == target:
               result.append((i,j))
    return result        

In [2]:
findpair([1,2,3,4,5,6],9)

[(2, 5), (3, 4)]

In [5]:
def findpair(nums, target):
    i = 0
    j = len(nums)-1
    while i<=j:
        if nums[i]+nums[j]>target:
            j = j-1
        elif nums[i]+nums[j]<target:
            i = i+1
        else:
            print(nums[i],nums[j])
            i+=1
            
findpair([1,2,3,4,5,6,7],9)            
        
        

2 7
3 6
4 5


In [6]:
# check if array has unique value 
myList = [1,20,30,44,5,56,57,19,10,31,12,13,14,35,16,27,58,19,21]
def isUnique(list):
    a = []
    for i in list:
        if i not in a :
            a.append(i)
        else:
            print(f"contains duplicate {i}")

In [7]:
isUnique(myList)

contains duplicate 19


In [16]:
# check for permutation
def check_permutation(list1, list2):
    if len(list1) != len(list2):
        return False
    list1.sort()
    list2.sort()
    if list1 == list2:
        return True
    else :
        return False

In [17]:
check_permutation([1,3,4],[1,4,3])

True

In [19]:
check_permutation(['a','b','c'],['c','a','b'])

True

In [40]:
# leet code 
# Rotate matrix by 90 degree
import numpy as np
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
myArray[0]

array([1, 2, 3])

In [41]:
np.transpose(myArray)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
def transpose(matrix):
    for row in range(len(matrix)):
        for col in range(row+1, len(matrix[0])):
            matrix[row][col],matrix[col][row] = matrix[col][row],matrix[row][col]
            print(row,col)
    print(matrix)
  

def transpose(matrix):
    trns =[]
    for col in range(len(matrix[0])):
        col_values = []
        for row in range(len(matrix)):
            col_values.append(matrix[row][col])
        trns.append(col_values)
    print(trns)

transpose(myArray)
            

[[1, 2, 3, 1], [4, 5, 6, 2], [7, 8, 9, 3]]


In [42]:
# clockwise rotation
def rotate_matrix(array):
    matrix = array.copy()
    for i in range(len(matrix)):
        for j in range(0,i):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
    for i in range(len(matrix)):
        matrix[i] = matrix[i][::-1]
    return matrix    
        

In [43]:
rotate_matrix(myArray)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [153]:
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
# anticlockwise rotation
def antirotate_matrix(Array):
    matrix = Array.copy()
    for i in range(len(matrix)):
        matrix[i] = matrix[i][::-1]
    for i in range(len(matrix)):
        for j in range(0,i):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j] # taking transpose
    
    return matrix    


In [168]:
antirotate_matrix(myArray)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [131]:
# During first iteration – 
# a[i][j] = Element at first index (leftmost corner top)= 1.
# a[j][n-1-i]= Rightmost corner top Element = 3.
# a[n-1-i][n-1-j] = Rightmost corner bottom element = 9.
# a[n-1-j][i] = Leftmost corner bottom element = 7.
# Move these elements in the clockwise direction. 
# During second iteration – 
# a[i][j] = 2.
# a[j][n-1-j] = 6.
# a[n-1-i][n-1-j] = 8.
# a[n-1-j][i] = 4. 
# Similarly, move these elements in the clockwise direction. 

In [28]:
len(myArray)

3

In [54]:
#### shifting all zeros of an array to the right 
a = [10,5,0,0,8,0,9,0]

# def shift_zero(a): # time complexity (O(n^2))
#     for i in range(len(a)):
#         if a[i] ==0: # 2 in this case
#             for j in range(i+1, len(a)):
#                 if a[j] !=0:
#                     a[i],a[j] = a[j],a[i]
#     print(a)
    
def shift_zero(a):
    low = 0
    i=0
    while i<len(a):
        if a[i] >0:
            a[low],a[i] = a[i],a[low]
            low+=1
            i+=1
        else:
            i+=1
    print(a)
shift_zero(a)            

# shift_zero(a) # time complexity (O(n^2))



# more efficient way to do this 
# def shift_zero_efficient(a): # time complexity O(n)
#     count = 0
#     for i in range(len(a)):

#         if a[i]!=0:
#             a[i], a[count] = a[count], a[i]
#             count = count+1
#     print(a)





[10, 5, 8, 9, 0, 0, 0, 0]


In [12]:
shift_zero_efficient(a)

[10, 5, 8, 9, 0, 0, 0, 0]


#### Rotation of An Array 

In [16]:
a = [ 1,2,3,4,5,6]
def left_rotation(a):
    temp = a[0]
    for i in range(len(a)):
        if i == len(a)-1:
            a[i] = temp
        else:
            a[i] = a[i+1]

    print(a)

left_rotation(a)

[2, 3, 4, 5, 6, 1]


In [55]:
#### Finding the leaders
#### if an array is in ascending order only one leader , descending order all are leaders
# leader is there is nothing bigger in the right side 
a = [7,10,4,3,6,5,2]

# def leader(a):
#     for i in range(len(a)):
#         bool = True # yes all leader

#         for j in range(i+1,len(a)):
#             if a[j]>=a[i]:
#                 bool = False
#                 break
    
#         if (bool == False):
#             print("not leader",a[i])
#         if bool == True:
#             print("leader",a[i])
# leader(a)
                

# effiencient way to find leaders
def leader(a):
    curr_leader = a[-1]
    print(curr_leader, 'leader')
    n = len(a)
    for i in range(n-2, -1,-1):
        if a[i] > curr_leader:
            print(a[i],'leader')
            curr_leader = a[i]
        else:
            print(a[i],'not leader')
            
            

leader(a)

2 leader
5 leader
6 leader
3 not leader
4 not leader
10 leader
7 not leader


In [39]:
### finding the maximum difference of two number in an array
# max( arr[j] - arr[i] ) such that j> i
a = [7,10,4,3,6,5,2]

# def max_diff(a): # n^2 time complexity 
#     max = a[1]-a[0]
#     for i in range(len(a)):
#         for j in range(i, len(a)):
#             res = (a[j]- a[i])
#             if res > max:
#                 max = res
#     return max
# max_diff(a) 

def max_diff(a):
    res = a[1]-a[0]
    min_val = a[0]    
    for i in range(len(a)):
        if a[i] - min_val > res:
            res = a[i]- min_val
        if a[i]< min_val:
            min_val = a[i]

    return res

max_diff(a)

    

3

In [4]:
### finding the second largest element 
# a = [ 5,20,12,40,10]
a = [10,10,10]

def get_largest(a):
    max = -1
    for i in a:
        if i> max:
            max = i
        else:
            pass
    return max

# get_largest(a)

def find_second_largest(a):
    res = -1
    max = get_largest(a)
    for i in a:
        if i != max:
            if i> res:
                res = i
            else:
                pass
    return res
find_second_largest(a)




####k efficient approach


-1

In [62]:
## finding the frequency of element in a sorted array

a = [10,10,10,20,30,40,40,50]
# a = [10,20,20,30]

def freq_find(a):
    i = 1
    freq = 1
    while i <= len(a):
        while i< len(a) and (a[i]== a[i-1]):
            freq = freq +1
            i = i+1
        print(a[i-1], freq)
        i = i + 1
        freq = 1


freq_find(a)



10 3
20 1
30 1
40 2
50 1


In [63]:
### finding maximum alternative even odd substring
a  = [5,10,20,6,3,8]

def max_evenodd(a):
    res = 1
    for i in range(1,len(a)):
        curr = 1
        for j in range(i+1, len(a)):
            if ((a[j]%2 == 0) and (a[j-1]%2 !=0)) or ((a[j]%2!= 0) and (a[j-1]%2 == 0)):
                curr += 1
            else:
                break

        res = max(res, curr)   
    return res

max_evenodd(a) 


3

In [3]:
### efficient approach
def even_odd(a):
    res = 1
    curr = 1
    for i in range(1, len(a)):
        if ((a[i]%2 == 0) and (a[i-1]%2 !=0)) or ((a[i]%2!= 0) and (a[i-1]%2 == 0)):
            curr+=1
            res = max(res,curr)
        else:
            curr = 1
    return res

even_odd(a)





3

### kadane algorithm

In [64]:
### find the sum of maximum sub array
a = [-5,1,-2,3,-1,2,-2]

def max_sum(a):
    res = a[0]
    maxending = a[0]
    for i in range(1,len(a)):
        maxending = max(maxending + a[i], a[i])
        print(maxending)
        res = max(res, maxending)
    return res

max_sum(a)

1
-1
3
2
4
2


4

### Circular sub array
connecting last element to the first array
here combination of kadane's algorithms


In [25]:
a = [-8,-4,3,-5,-4]

def normalmaxsum(a):
    res  = a[0]
    maxending = a[0]
    for i in range(1, len(a)):
        maxending = max(a[i], maxending+a[i])
        res = max(res,maxending)
    return res

def circular_sum(a):
    # total sum - min(using kadane algorithm)
    max_normal = normalmaxsum(a)
    if max_normal < 0: # it means everything is negative in the array
        return max_normal
    total_sum = sum(a)
    # here we dont need to modify kadane for minimum sum if we just change the sign
    min = -normalmaxsum([-x for x in a])
    max_circular = total_sum - min
    return max(max_circular, max_normal)



circular_sum(a)



3

### Majority of an array 
majority means if the frequency of element is greater than n/2 


In [44]:
a = [11,11,-2,-5,11,0]

def majority(a):
    for i in range(len(a)):
        count = 1
        for j in range(i+1, len(a)):
            if a[i] == a[j]:
                count = count + 1
        # print(count)
        if count> len(a)/2:
            return a[i]
        else:
            return -1

### more efficient way to find the majority 
def majority(a):
    res = 0
    count = 1
    for i in range(1, len(a)):
        if a[i] == a[res]:
            count +=1 
        else:
            count -= 1

        if count == 0:
            res = 0
            count = 1

    #### verifying if the index is majority 
    n = 0
    for i in range(0, len(a)):
       if a[i] == a[res]:
           n = n + 1
    if n> len(a)/2:
        return a[res],n
    else:
        return -1

majority(a)



# majority(a)






-1

#### finding the minimum cosecutive flips to make binary array same 


In [52]:
a = [1,1,0,0,1,1,1,1,0]

def finding_groups(a):
    # first count the group of 0, and 1
    st = []
    count_1 = 0
    for i in range(0, len(a)):
        if a[i] == 1:
            st.append(1)
        else:
            if len(st) > 0:
                count_1 += 1
                while len(st) > 0 :
                    del st[-1]
    if len(st):
        count_1 += 1
    return count_1

def min_flips(a):
     ## flipping the second group always gives the minimum of equal number of flips 
    for i in range(0, len(a)):
        if a[i] != a[i-1]:
            # check if its beginning of end by comparing with zero
            if a[i] != a[0]:
                # its an beginning of  a group
                print("from", i ," to")
            else:
                # ending of the group 
                print((i-1))

    if a[-1] != a[0]:
        print(i)

min_flips(a) 


-1
from 2  to
3
from 8  to
8


### Rain water trap problem

In [67]:
a = [3,1,2, 3,7]


def trap_water(a):
    res = 0
    for i in range(1, len(a)):  # time complexity Q(n^2)
        lmax = a[i]
        for j in range(0, i):
            lmax = max(lmax, a[j])
        rmax = a[i]
        for j in range(i, len(a)):
            rmax = max(rmax, a[j])
        res = res + min(rmax, lmax) - a[i]
    return res

def trap_water(a): # more efficient method 
    res = 0
    lmax = [0]*len(a)
    rmax = [0]*len(a)

    lmax[0] = a[0]
    for i in range(1,len(a)):
        lmax[i] = max(a[i], lmax[i-1])
    rmax[-1] = a[-1]
    for i in range(len(a)-2, -1,-1):
        rmax[i] = max(a[i], rmax[i+1])
    
    for i in range(1,len(a)-1):
        res =res+  min(lmax[i], rmax[i])- a[i]
    return res





trap_water(a)


[3, 3, 3, 3, 7]


#### Window Sliding Technique

In [12]:
# finding the n-bonacci number using sliding window s
# if n = 3 then (0,0,1)
# if n = 2 then (0,1)


def nbonnaci(n, m):
    numbers = [0]*m
    numbers[n-1] = 1
    sum_last_3 = 1
    for i in range(n,m):
        numbers[i] = sum_last_3
        sum_last_3 = sum_last_3 +  numbers[i] - numbers[i-n]

    print(numbers)



nbonnaci(2,10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [18]:
#### given an array and find if it has an equilibrium point
a = [3,4,8,-9,20,6]

def isequi(a): # O(n^2) time complexity
    for i in range(len(a)):
        sum_r = 0
        sum_l = 0
        for j in range(i+1, len(a)):
            sum_r += a[j]
        
        for k in range(0,i):
            sum_l += a[k]
        
        if sum_r == sum_l:
            return (i,True)
        

# efficient approach 

def isequi(a):
    total_sum = sum(a)
    l_sum = 0
    for i in range(0, len(a)):
        if l_sum == total_sum - a[i]:
            return (i,True)

        l_sum += a[i]
        total_sum -= a[i]




isequi(a)


(4, True)

In [23]:
### STock price max profit 
a = [1,5,3,8,12]
a = [30,20,10]
a = [1,5,3,1,2,8]

def profit(a):
    profit_sum = 0
    for i in range(1,len(a)):
        if a[i] > a[i-1]:
            profit_sum += a[i] - a[i-1]
    return profit_sum

profit(a)

11